### ISSUE TITLE
Unpaired quotation marks handled strangely

### ISSUE THREAD

**Issue by asquared31415** [louisdh/terminal#3] opened 2018-01-07 04:16 UTC
It appears that when a quotation mark is seen by the terminal, it strips itself and the closing quotation mark and the result is taken literally.  When the quotation mark is unpaired, instead of simply causing an error or assuming to close the quotation mark, the last character is stripped.  This means that “rm shows r: command not found, but “rmz to show the usage for the rm command.

Related to this issue is the other issue I submitted, where entering only a “ crashes the app.  The terminal is probably trying to strip the final character, but not finding one, and crashing.

Sample crash report: https://pastebin.com/NTthrH2F

**Comment by holzschu** [comment] 2018-01-07 11:46
I think that comes from ios_system, and the way it parses quotes. I'll have a look.

**Comment by holzschu** [comment] 2018-01-07 15:29
Yes, can confirm the issue was caused by ios_system. I assumed a quote would always be paired. I have removed that assumption now. @louisdh , you probably need to merge with the new library. I also improved the error messages.

**Comment by louisdh** [comment] 2018-01-07 19:01
I've merged the latest ios_system. Thanks @holzschu, and thanks @asquared31415 for reporting!

**Closed by louisdh** 2018-01-07 19:01 UTC
